alert("JS已启动！");
const FAKE_DELAY = 50;
function delay() { return new Promise(r => setTimeout(r, FAKE_DELAY)); }
async function getAllUsers() { await delay(); return JSON.parse(localStorage.getItem("db_users") || "{}"); }
async function saveAllUsers(users) { await delay(); localStorage.setItem("db_users", JSON.stringify(users)); }
async function getFavData() { await delay(); return JSON.parse(localStorage.getItem("db_favs") || "[]"); }
async function saveFavData(data) { await delay(); localStorage.setItem("db_favs", JSON.stringify(data)); }
async function getHistoryData() { await delay(); return JSON.parse(localStorage.getItem("db_hist") || "[]"); }
async function saveHistoryData(data) { await delay(); localStorage.setItem("db_hist", JSON.stringify(data)); }
async function getCommentData() { await delay(); return JSON.parse(localStorage.getItem("db_comments") || "[]"); }
async function saveCommentData(data) { await delay(); localStorage.setItem("db_comments", JSON.stringify(data)); }
async function getNextCommentId() { const all = await getCommentData(); if (all.length === 0) return 1; return Math.max(...all.map(c => c.id || 0)) + 1; }
function coverUrl(comicId) { return `https://picsum.photos/seed/comic${comicId}/300/400`; }
function pageImgUrl(comicId, pageNum) { return `https://picsum.photos/seed/comic${comicId}_p${pageNum}/600/800`; }
function getTotalPages() { return 5; }
const comics = [
    { id: 1, title: "仙王的日常生活", chapter: "第320话", tag: "玄幻" },
    { id: 2, title: "都市极品神医", chapter: "第188话", tag: "都市" },
    { id: 3, title: "星河漫步", chapter: "第56话", tag: "科幻" },
    { id: 4, title: "甜蜜契约", chapter: "第102话", tag: "恋爱" },
    { id: 5, title: "暗夜追踪", chapter: "第77话", tag: "悬疑" },
    { id: 6, title: "剑来", chapter: "第215话", tag: "玄幻" },
    { id: 7, title: "总裁在上", chapter: "第140话", tag: "都市" },
    { id: 8, title: "机械纪元", chapter: "第39话", tag: "科幻" },
    { id: 9, title: "热血高校", chapter: "第263话", tag: "热血" },
    { id: 10, title: "爆笑江湖", chapter: "第91话", tag: "搞笑" },
    { id: 11, title: "龙族崛起", chapter: "第48话", tag: "奇幻" },
    { id: 12, title: "全职法师", chapter: "第302话", tag: "玄幻" },
    { id: 13, title: "狐妖小红娘", chapter: "第156话", tag: "恋爱" },
    { id: 14, title: "星海征程", chapter: "第63话", tag: "冒险" },
    { id: 15, title: "心理罪", chapter: "第85话", tag: "悬疑" },
    { id: 16, title: "镇魂街", chapter: "第198话", tag: "热血" },
    { id: 17, title: "西行纪", chapter: "第112话", tag: "古风" },
    { id: 18, title: "一人之下", chapter: "第230话", tag: "玄幻" },
    { id: 19, title: "斗破苍穹", chapter: "第410话", tag: "玄幻" },
    { id: 20, title: "凤囚凰", chapter: "第89话", tag: "古风" },
];
let currentUser = null, favList = [], currentView = "home", currentComic = null, currentPage = 0;
let readerScale = 1, readerTranslateX = 0, readerTranslateY = 0, replyTo = null;
async function apiRegister(u, p) { const users = await getAllUsers(); if (users[u]) return { ok: false, msg: "该用户名已被注册" }; users[u] = { password: p, createdAt: Date.now() }; await saveAllUsers(users); return { ok: true, msg: "✅ 注册成功！请登录" }; }
async function apiLogin(u, p) { const users = await getAllUsers(); if (!users[u] || users[u].password !== p) return { ok: false }; return { ok: true }; }
async function apiGetFavorites(u) { const all = await getFavData(); return all.filter(f => f.username === u).map(f => f.comic_id); }
async function apiAddFavorite(u, cid) { const all = await getFavData(); all.push({ username: u, comic_id: cid }); await saveFavData(all); }
async function apiRemoveFavorite(u, cid) { let all = await getFavData(); all = all.filter(f => !(f.username === u && f.comic_id === cid)); await saveFavData(all); }
async function apiGetHistory(u) { const all = await getHistoryData(); return all.filter(h => h.username === u).sort((a, b) => b.viewed_at - a.viewed_at).slice(0, 20).map(h => ({ id: h.comic_id, time: h.viewed_at })); }
async function apiAddHistory(u, cid) { let all = await getHistoryData(); all = all.filter(h => !(h.username === u && h.comic_id === cid)); all.push({ username: u, comic_id: cid, viewed_at: Date.now() }); if (all.length > 100) all = all.slice(-100); await saveHistoryData(all); }
async function apiGetComments(cid) { const all = await getCommentData(); return all.filter(c => c.comic_id === cid).sort((a, b) => a.time - b.time); }
async function apiAddComment(cid, u, txt, pid, pu) { const id = await getNextCommentId(); const all = await getCommentData(); all.push({ id, comic_id: cid, username: u, text: txt, time: Date.now(), parent_id: pid || null, parent_username: pu || null }); await saveCommentData(all); }
async function apiGetRanking() { const allFavs = await getFavData(); const m = {}; allFavs.forEach(f => { m[f.comic_id] = (m[f.comic_id] || 0) + 1; }); return comics.map(c => ({ ...c, favCount: m[c.id] || 0 })).filter(c => c.favCount > 0).sort((a, b) => b.favCount - a.favCount).slice(0, 20); }
function timeAgo(ts) { const s = Math.floor((Date.now() - ts) / 1000); if (s < 60) return "刚刚"; if (s < 3600) return Math.floor(s / 60) + "分钟前"; if (s < 86400) return Math.floor(s / 3600) + "小时前"; return Math.floor(s / 86400) + "天前"; }
function openLogin() { if (currentUser) { if (confirm(`退出「${currentUser}」？`)) logout(); return; } document.getElementById("loginOverlay").style.display = "flex"; document.getElementById("loginUsername").value = ""; document.getElementById("loginPassword").value = ""; document.getElementById("loginMsg").textContent = ""; }
function closeLogin() { document.getElementById("loginOverlay").style.display = "none"; }
async function doRegister() { const u = document.getElementById("loginUsername").value.trim(); const p = document.getElementById("loginPassword").value.trim(); if (!u || !p) { document.getElementById("loginMsg").textContent = "⚠️ 不能为空"; return; } if (p.length < 4) { document.getElementById("loginMsg").textContent = "⚠️ 密码至少4位"; return; } document.getElementById("loginMsg").textContent = "注册中..."; const r = await apiRegister(u, p); document.getElementById("loginMsg").textContent = r.msg; }
async function doLogin() { const u = document.getElementById("loginUsername").value.trim(); const p = document.getElementById("loginPassword").value.trim(); document.getElementById("loginMsg").textContent = "登录中..."; const r = await apiLogin(u, p); if (!r.ok) { document.getElementById("loginMsg").textContent = "⚠️ 用户名或密码错误"; return; } currentUser = u; favList = await apiGetFavorites(u); updateUserUI(); closeLogin(); if (currentView === "favorites") showFavorites(); else if (currentView === "history") showHistory(); else if (currentView === "ranking") showRanking(); else renderComics("全部"); }
function logout() { currentUser = null; favList = []; updateUserUI(); renderComics("全部"); switchNav("home"); currentView = "home"; }
function updateUserUI() { const btn = document.getElementById("btnUser"); if (currentUser) { btn.textContent = `👤 ${currentUser}`; btn.className = "btn-user logged-in"; } else { btn.textContent = "👤 登录"; btn.className = "btn-user"; } }
function isFav(id) { return favList.includes(id); }
function makeComicCard(c, rank) { const loved = isFav(c.id); const fb = currentUser ? `<button class="card-fav-btn" onclick="event.stopPropagation();toggleFavCard(${c.id},this)">${loved ? '❤️' : '🤍'}</button>` : ""; const badge = rank ? `<span class="rank-badge ${rank===1?'gold':rank===2?'silver':rank===3?'bronze':''}">${rank}</span>` : ""; const extra = c.favCount !== undefined ? `<div class="comic-chapter">❤️ ${c.favCount} 人收藏</div>` : `<div class="comic-chapter">${c.chapter}</div>`; return `<div class="comic-card"><div class="comic-cover" onclick="openComic(${c.id})"><img src="${coverUrl(c.id)}" alt="${c.title}" loading="lazy">${badge}${fb}</div><div class="comic-info" onclick="openComic(${c.id})"><div class="comic-title">${c.title}</div>${extra}</div></div>`; }
function renderList(list, title, sb, st, sr) { document.getElementById("sectionTitle").textContent = title; document.getElementById("bannerArea").style.display = sb ? "block" : "none"; document.getElementById("tagArea").style.display = st ? "flex" : "none"; const g = document.getElementById("comicGrid"), e = document.getElementById("emptyMsg"); if (list.length === 0) { g.innerHTML = ""; e.style.display = "block"; e.innerHTML = currentUser ? "😢 暂无内容" : "😢 请先登录"; } else { e.style.display = "none"; g.innerHTML = list.map((c, i) => makeComicCard(c, sr ? i + 1 : null)).join(""); } }
function renderComics(tag) { currentView = "home"; renderList(tag === "全部" ? comics : comics.filter(c => c.tag === tag), "🔥 热门漫画", true, true, false); switchNav("home"); }
function filterTag(el) { document.querySelectorAll(".tag").forEach(t => t.classList.remove("active")); el.classList.add("active"); renderComics(el.textContent); }
async function showFavorites() { currentView = "favorites"; if (!currentUser) { openLogin(); return; } favList = await apiGetFavorites(currentUser); renderList(comics.filter(c => favList.includes(c.id)), "❤️ 我的收藏", false, false, false); switchNav("fav"); }
async function showHistory() { currentView = "history"; if (!currentUser) { openLogin(); return; } const his = await apiGetHistory(currentUser); const hc = his.map(h => { const c = comics.find(co => co.id === h.id); return c || { id: h.id, title: "未知", chapter: "", tag: "" }; }); renderList(hc, "🕐 阅读历史", false, false, false); switchNav("his"); }
async function showRanking() { currentView = "ranking"; const ranked = await apiGetRanking(); renderList(ranked, "🏆 收藏排行榜", false, false, true); switchNav("rank"); }
function switchNav(a) { ["Home","Fav","His","Rank"].forEach(s => { document.getElementById("nav"+s).classList.toggle("nav-active", a === s.toLowerCase()); }); }
async function toggleFavCard(cid, btn) { if (!currentUser) { openLogin(); return; } if (favList.includes(cid)) { await apiRemoveFavorite(currentUser, cid); favList = favList.filter(id => id !== cid); btn.innerHTML = "🤍"; } else { await apiAddFavorite(currentUser, cid); favList.push(cid); btn.innerHTML = "❤️"; } if (currentView === "favorites") showFavorites(); else if (currentView === "ranking") showRanking(); }
async function toggleFavInReader() { if (!currentUser || !currentComic) return; const btn = document.getElementById("btnFavInReader"); if (favList.includes(currentComic.id)) { await apiRemoveFavorite(currentUser, currentComic.id); favList = favList.filter(id => id !== currentComic.id); btn.textContent = "🤍"; } else { await apiAddFavorite(currentUser, currentComic.id); favList.push(currentComic.id); btn.textContent = "❤️"; } }
function searchComic() { currentView = "home"; const kw = document.getElementById("searchInput").value.trim(); if (!kw) return renderComics("全部"); const results = comics.filter(c => c.title.includes(kw)); if (results.length === 0) { document.getElementById("bannerArea").style.display = "none"; document.getElementById("tagArea").style.display = "none"; document.getElementById("sectionTitle").textContent = "🔍 搜索结果"; document.getElementById("comicGrid").innerHTML = ""; document.getElementById("emptyMsg").style.display = "block"; document.getElementById("emptyMsg").innerHTML = "😢 没找到"; } else { renderList(results, "🔍 搜索结果", false, false, false); } switchNav("home"); }
async function openComic(cid) { if (!currentUser) { openLogin(); return; } currentComic = comics.find(c => c.id === cid); currentPage = 0; readerScale = 1; readerTranslateX = 0; readerTranslateY = 0; replyTo = null; await apiAddHistory(currentUser, cid); document.getElementById("homePage").style.display = "none"; document.getElementById("readerPage").style.display = "block"; document.getElementById("readerTitle").textContent = currentComic.title; document.getElementById("chapterName").textContent = currentComic.chapter; document.getElementById("btnFavInReader").textContent = isFav(cid) ? "❤️" : "🤍"; document.getElementById("readerTip").classList.remove("hide"); setTimeout(() => document.getElementById("readerTip").classList.add("hide"), 4000); window.scrollTo(0, 0); updateReader(); loadComments(); }
function updateReader() { const total = getTotalPages(); document.getElementById("readerImg").src = pageImgUrl(currentComic.id, currentPage + 1); document.getElementById("pageInfo").textContent = (currentPage + 1) + " / " + total; readerScale = 1; readerTranslateX = 0; readerTranslateY = 0; applyReaderTransform(); document.querySelectorAll(".btn-page")[0].style.opacity = currentPage === 0 ? 0.3 : 1; document.querySelectorAll(".btn-page")[1].style.opacity = currentPage === total - 1 ? 0.3 : 1; }
function applyReaderTransform() { document.getElementById("readerImg").style.transform = `translate(${readerTranslateX}px, ${readerTranslateY}px) scale(${readerScale})`; }
function nextPage() { if (currentPage < getTotalPages() - 1) { currentPage++; updateReader(); } }
function prevPage() { if (currentPage > 0) { currentPage--; updateReader(); } }
function renderReplyIndicator() { const c = document.querySelector(".comment-input-row"); const o = document.getElementById("replyIndicator"); if (o) o.remove(); if (replyTo) { const d = document.createElement("div"); d.id = "replyIndicator"; d.className = "reply-indicator"; d.innerHTML = `回复 @${replyTo.username} <button onclick="cancelReply()">✕</button>`; c.parentNode.insertBefore(d, c); } }
function cancelReply() { replyTo = null; const o = document.getElementById("replyIndicator"); if (o) o.remove(); document.getElementById("commentInput").placeholder = "写下你的评论..."; }
async function loadComments() { if (!currentComic) return; const all = await apiGetComments(currentComic.id); const top = all.filter(c => !c.parent_id); const reps = all.filter(c => c.parent_id); document.getElementById("commentCount").textContent = all.length; const list = document.getElementById("commentList"); if (all.length === 0) { list.innerHTML = '<div class="comment-empty">💬 暂无评论</div>'; return; } list.innerHTML = top.map(c => { const cr = reps.filter(r => r.parent_id === c.id); const rh = cr.map(r => `<div class="comment-reply-item"><div class="comment-user">${r.username} → ${r.parent_username}</div><div class="comment-text">${r.text}</div class="comment-time">${timeAgo(r.time)}</div><button class="comment-reply-btn" onclick="startReply(${c.id},'${c.username}')">回复</button></div>`).join(""); return `<div class="comment-item"><div class="comment-user">${c.username}</div><div class="comment-text">${c.text}</div><div class="comment-time">${timeAgo(c.time)}</div><button class="comment-reply-btn" onclick="startReply(${c.id},'${c.username}')">回复</button>${cr.length > 0 ? '<div class="comment-replies">'+rh+'</div>' : ''}</div>`; }).join(""); }
function startReply(cid, uname) { replyTo = { id: cid, username: uname }; document.getElementById("commentInput").placeholder = `回复 @${uname}：`; document.getElementById("commentInput").focus(); renderReplyIndicator(); }
async function sendComment() { if (!currentUser) { alert("请先登录"); return; } const input = document.getElementById("commentInput"); const text = input.value.trim(); if (!text) return; if (text.length > 200) { alert("评论最多200字"); return; } await apiAddComment(currentComic.id, currentUser, text, replyTo ? replyTo.id : null, replyTo ? replyTo.username : null); input.value = ""; replyTo = null; cancelReply(); loadComments(); }
(function initTouch() { const a = document.getElementById("readerArea"); let sx = 0, sy = 0, stx = 0, sty = 0, ss = 1, sd = 0, ip = false, mv = false; a.addEventListener("touchstart", (e) => { if (!currentComic) return; if (e.touches.length === 1) { sx = e.touches[0].clientX; sy = e.touches[0].clientY; ip = false; mv = false; stx = readerTranslateX; sty = readerTranslateY; } else if (e.touches.length === 2) { ip = true; sd = Math.hypot(e.touches[0].clientX - e.touches[1].clientX, e.touches[0].clientY - e.touches[1].clientY); ss = readerScale; } }, { passive: false }); a.addEventListener("touchmove", (e) => { if (!currentComic) return; if (ip && e.touches.length === 2) { e.preventDefault(); const d = Math.hypot(e.touches[0].clientX - e.touches[1].clientX, e.touches[0].clientY - e.touches[1].clientY); readerScale = Math.max(1, Math.min(3, ss * (d / sd))); applyReaderTransform(); } else if (!ip && e.touches.length === 1) { const dx = e.touches[0].clientX - sx; if (Math.abs(dx) > 8) mv = true; if (readerScale > 1) { readerTranslateX = stx + dx; readerTranslateY = sty + (e.touches[0].clientY - sy); applyReaderTransform(); } } }, { passive: false }); a.addEventListener("touchend", (e) => { if (!currentComic) return; if (!ip && mv && readerScale === 1) { const dx = (e.changedTouches[0]?.clientX || sx) - sx; if (dx < -50) nextPage(); else if (dx > 50) prevPage(); } stx = readerTranslateX; sty = readerTranslateY; ip = false; mv = false; }); a.addEventListener("dblclick", () => { if (!currentComic) return; if (readerScale > 1) { readerScale = 1; readerTranslateX = 0; readerTranslateY = 0; } else { readerScale = 2; } applyReaderTransform(); stx = readerTranslateX; sty = readerTranslateY; }); })();
function goHome() { document.getElementById("readerPage").style.display = "none"; document.getElementById("homePage").style.display = "block"; if (currentView === "favorites") showFavorites(); else if (currentView === "history") showHistory(); else if (currentView === "ranking") showRanking(); else renderComics("全部"); currentComic = null; }
if ('serviceWorker' in navigator) { navigator.serviceWorker.register('./sw.js').then(() => console.log('✅ PWA')).catch(e => console.log(e)); }
updateUserUI();
renderComics("全部");
